### ISSUE TITLE
Excellent! 

### ISSUE THREAD

**Issue by zhangfq-chemistry** [GreenLightning/gpu-font-rendering#1]
How to build one mesh from several words consists of empty space? Thanks!

**Comment by GreenLightning** [comment]
Hi, I don't really understand the question.

You can see how the mesh is built [here](https://github.com/GreenLightning/gpu-font-rendering/blob/aa739f037b99c7218313066da999c5ba3eaf570f/source/font.cpp#L555). This already creates a single mesh for the whole string passed into the `draw` method. It generates two triangles / one quad per glyph, but the triangles can be positioned however you want, e.g. for drawing multiple glyphs on top of each other. For whitespace characters no triangles are generated as nothing needs to be drawn.

I hope that helps!
